# Generated by Django 5.2.9 on 2025-12-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='seat_price',
            field=models.IntegerField(blank=True, default=499, null=True),
        ),
    ]
